### PR TITLE
Initial setup scaffolding of rails app

### PR DESCRIPTION
**Pull request by hmvitous**
## Changes proposed with this pull request:

* Sets up the rails app scaffolding
* Cleans out commented code and formats the code that is left.

## Gems Added:
* rack-cors
* Factory-bot
* Shoulda matchers
* pry-byebug
* pry-rails

### CODE REVIEW

**Review by Carltesio — COMMENTED** [review]
Write the gems you have added as well in the PR request

**Comment by Carltesio** [comment]
merging ok from me now

**Comment by dernathul** [comment]
ok

**Comment by hmvitous** [comment]
Added the gems that were added into the PR

**Pull request merged**
